spring:
  application:
    name: user
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usert?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
    hikari:
      auto-commit: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: luna.user
  configuration:
    use-generated-keys: true
    cache-enabled: false
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: bus/refresh

test:
  auto:
    refresh: yes, 88
