spring:
  application:
    name: webdoor

feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
