spring:
  application:
    name: webdoor

feign:
  hystrix:
    enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 3000
