spring:
  application:
    name: webdoor
  cloud:
    gateway:
     discovery:
        locator:
         enabled: true

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: hystrix.stream
    
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 3000
