spring:
  application:
    name: webdoor

feign:
  hystrix:
    enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 3000
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
